### ISSUE TITLE
Ensure that game has a solution

### ISSUE THREAD

**Issue by tesar-tech** [John-Experimental/GamesInBlazor#12]
This would be useful to have. By my counting non-solution game is about 15 % rate.

I was thinking about implementation, should not be hard to do.

Maybe we can add "setting" to allow "solutionless" game.

let me know what you think!

**Comment by John-Experimental** [comment]
Yes absolutely. Had already taken an advance on it by allowing the grid to be good looking at a 15 card layout. The implementation is not too difficult as I can repurpose existing code to do it.

I've been struggling with the DI pipeline though. Once that's fixed this is the first issue I'll address.

**Comment by John-Experimental** [comment]
#14 done
